# Generated by Django 6.0.6 on 2026-08-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_otp'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
