# Generated by Django 6.0.6 on 2026-08-09 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('yards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('agent_assigned', 'Agent Assigned'), ('agent_en_route', 'Agent En Route'), ('agent_arrived', 'Agent Arrived'), ('picked_up', 'Picked Up'), ('at_yard', 'At Yard'), ('dumped', 'Dumped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pickup_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('on_demand', 'On Demand')], default='on_demand', max_length=20)),
                ('scheduled_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_weight_kg', models.FloatField(blank=True, null=True)),
                ('actual_weight_kg', models.FloatField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('pickup_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='users.customeraddress')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='yards.wastetype')),
                ('yard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='yards.yard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
