# Generated by Django 6.0.6 on 2026-07-31 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('lattitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='YardWasteCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.FloatField()),
                ('current_fill_kg', models.FloatField(default=0.0)),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yards.wastetype')),
                ('yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yards.yard')),
            ],
            options={
                'unique_together': {('yard', 'waste_type')},
            },
        ),
        migrations.AddField(
            model_name='yard',
            name='waste_types',
            field=models.ManyToManyField(through='yards.YardWasteCapacity', to='yards.wastetype'),
        ),
    ]
